import { fromZonedTime, formatInTimeZone } from "date-fns-tz";

/** The only timezones the admin can pick — kept short and curated rather than
 * an exhaustive IANA list, per the lean-V1 scope. Both the find-a-time form's
 * Select and the availability route's zod validation read from this single
 * source of truth so they can never drift out of sync. */
export const TIMEZONES = [
  { value: "America/Los_Angeles", label: "Pacific (PT)" },
  { value: "America/Denver", label: "Mountain (MT)" },
  { value: "America/Chicago", label: "Central (CT)" },
  { value: "America/New_York", label: "Eastern (ET)" },
] as const;

export type TimezoneValue = (typeof TIMEZONES)[number]["value"];

/** Grid row spacing / the Nylas availability query's `intervalMinutes` — kept
 * as one named constant so the API call and the grid's row generation can
 * never silently drift apart (the route must pass this explicitly rather
 * than relying on the Nylas wrapper's own default). */
export const AVAILABILITY_INTERVAL_MINUTES = 30;

/** True only for a real calendar date in "YYYY-MM-DD" form — rejects
 * impossible dates like 2026-02-30 that the shape-only regex would allow
 * through (which would otherwise silently become NaN downstream and surface
 * as a misleading "couldn't reach Nylas" error). */
export function isValidDateString(dateStr: string) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) return false;
  const [y, m, d] = dateStr.split("-").map(Number);
  const date = new Date(Date.UTC(y, m - 1, d));
  return (
    date.getUTCFullYear() === y && date.getUTCMonth() === m - 1 && date.getUTCDate() === d
  );
}

/** True for a real "HH:mm" 24-hour time. */
export function isValidTimeString(timeStr: string) {
  if (!/^\d{2}:\d{2}$/.test(timeStr)) return false;
  const [h, m] = timeStr.split(":").map(Number);
  return h >= 0 && h <= 23 && m >= 0 && m <= 59;
}

/** True if an "HH:mm" time falls on an AVAILABILITY_INTERVAL_MINUTES boundary
 * (e.g. :00/:30 for the default 30-minute interval). The grid's rows are
 * generated by stepping from workingHoursStart in that same interval
 * (generateTimeRows), and Nylas's returned slots are rounded to it too
 * (see getCollectiveAvailability's roundTo) — a working-hours start/end off
 * that boundary would generate rows Nylas's slots can never land on, making
 * every found slot silently unclickable. Only guarantees alignment while
 * AVAILABILITY_INTERVAL_MINUTES divides 60 (e.g. 15/20/30) — Nylas's roundTo
 * is anchored to the hour, not to workingHoursStart, so an interval like 45
 * would still drift even with this check passing. Callers must validate with
 * isValidTimeString first. */
export function isOnIntervalBoundary(timeStr: string) {
  const [, m] = timeStr.split(":").map(Number);
  return m % AVAILABILITY_INTERVAL_MINUTES === 0;
}

/** Converts a "YYYY-MM-DD" date + "HH:mm" time, interpreted as wall-clock time
 * in `timezone`, into a unix-seconds timestamp. Used to turn the admin's date
 * range into the UTC window Nylas's availability API expects. Callers must
 * validate `dateStr`/`timeStr` first (isValidDateString/isValidTimeString) —
 * this does not itself guard against malformed input. */
export function zonedDateTimeToUnix(dateStr: string, timeStr: string, timezone: string) {
  const utcDate = fromZonedTime(`${dateStr}T${timeStr}:00`, timezone);
  return Math.floor(utcDate.getTime() / 1000);
}

/** Returns the "YYYY-MM-DD" for the day after `dateStr`. Used to build an
 * end-of-range boundary as the NEXT day's midnight rather than "23:59" —
 * Nylas requires start_time/end_time to be exact multiples of 5 minutes, and
 * while midnight always lands on one (every supported timezone's UTC offset
 * is a whole number of hours), 23:59 never does. */
export function nextDayString(dateStr: string) {
  return addDaysToDateString(dateStr, 1);
}

/** Adds `days` (can be negative) to a "YYYY-MM-DD" string, handling
 * month/year rollover via UTC-based date arithmetic — never touches wall-clock
 * time or a timezone, this is pure calendar-date math. */
export function addDaysToDateString(dateStr: string, days: number) {
  const [y, m, d] = dateStr.split("-").map(Number);
  const date = new Date(Date.UTC(y, m - 1, d + days));
  const year = date.getUTCFullYear();
  const month = String(date.getUTCMonth() + 1).padStart(2, "0");
  const day = String(date.getUTCDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

/** 0 (Sunday) through 6 (Saturday) for a "YYYY-MM-DD" string. */
export function dayOfWeek(dateStr: string) {
  const [y, m, d] = dateStr.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d)).getUTCDay();
}

export function isWeekendDateString(dateStr: string) {
  const day = dayOfWeek(dateStr);
  return day === 0 || day === 6;
}

/** "YYYY-MM-DD" -> "Mon Aug 17". Pure calendar-date formatting, no timezone
 * conversion needed since a date string already represents a specific day
 * regardless of who's viewing it. */
export function formatDateLabel(dateStr: string) {
  const [y, m, d] = dateStr.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d)).toLocaleDateString("en-US", {
    weekday: "short",
    month: "short",
    day: "numeric",
    timeZone: "UTC",
  });
}

/** The same date with the year, for spelling out what a native date input is
 * showing.
 *
 * `<input type="date">` renders in the BROWSER's locale, so one field reads
 * 01.09.2026 in Germany and 9/1/2026 in the US and no attribute changes it.
 * Written with the month by name, "Tue, Sep 1, 2026" cannot be misread as the
 * ninth of January whichever way round the reader expects the numbers. */
export function spellOutDate(dateStr: string) {
  if (!isValidDateString(dateStr)) return "";
  const [y, m, d] = dateStr.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d)).toLocaleDateString("en-US", {
    weekday: "short",
    month: "short",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  });
}

/** "HH:mm" (24h) -> "9:00 AM" — a plain time-of-day label, not tied to any
 * specific date or timezone conversion. */
export function formatTimeLabel(timeStr: string) {
  const [h, m] = timeStr.split(":").map(Number);
  const period = h >= 12 ? "PM" : "AM";
  const hour12 = h % 12 === 0 ? 12 : h % 12;
  return `${hour12}:${String(m).padStart(2, "0")} ${period}`;
}

/** Generates "HH:mm" row labels from `startTime` up to (but not including)
 * `endTime`, stepping by `AVAILABILITY_INTERVAL_MINUTES` — the same grid the
 * Nylas availability query itself is computed against. */
export function generateTimeRows(startTime: string, endTime: string) {
  const [startH, startM] = startTime.split(":").map(Number);
  const [endH, endM] = endTime.split(":").map(Number);
  const startMinutes = startH * 60 + startM;
  const endMinutes = endH * 60 + endM;

  const rows: string[] = [];
  for (let t = startMinutes; t < endMinutes; t += AVAILABILITY_INTERVAL_MINUTES) {
    const h = Math.floor(t / 60);
    const m = t % 60;
    rows.push(`${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`);
  }
  return rows;
}

/** Splits a unix-seconds instant into its "YYYY-MM-DD" date and "HH:mm" time
 * as seen in `timezone` — the inverse of zonedDateTimeToUnix, used to place a
 * returned availability slot into its grid cell. */
export function zonedDateTimeParts(unixSeconds: number, timezone: string) {
  const date = new Date(unixSeconds * 1000);
  return {
    date: formatInTimeZone(date, timezone, "yyyy-MM-dd"),
    time: formatInTimeZone(date, timezone, "HH:mm"),
  };
}

export type AvailabilityWindow = { dayOfWeek: number; startTime: string; endTime: string };

/** True if a candidate slot falls within a member's OWN stated weekly
 * availability (set on /me), checked in the member's OWN timezone — not the
 * admin search's timezone, since a member's "2-5pm" means 2-5pm where THEY
 * are, regardless of what zone the admin searched in.
 *
 * A member with no `timezone` set has never saved anything on /me at all —
 * treated as unrestricted (calendar free/busy alone still applies) rather
 * than fully blocked, so existing members already in the system aren't
 * silently locked out of every search the moment this shipped. `timezone` is
 * always written on every /me save regardless of how many days are enabled
 * (see api/me/route.ts), so once it's set, a member who saved with EVERY day
 * switched off has zero `memberAvailability` rows on purpose — they get
 * rejected for every day below, same as anyone who left just one day off.
 * Not "no rows = unrestricted," only "never saved at all = unrestricted."
 *
 * Windows themselves can't cross midnight (the /me form only accepts
 * startTime < endTime ranges, of which a day may now have several), so a
 * slot that spans local
 * midnight in the member's zone can never fit inside one — rejecting it is
 * mathematically correct, not just conservative. Known limitation this
 * implies: for a member in a timezone far from the admin's search zone (the
 * admin only searches within 4 curated US zones, but a member can set any
 * IANA zone on /me), ordinary business-hours slots can land near local
 * midnight for them and get dropped even during hours they'd otherwise
 * accept — there's currently no way for a member to express an
 * overnight-spanning window at all. */
export function slotMatchesMemberAvailability(
  slot: { startUnix: number; endUnix: number },
  memberTimezone: string | null,
  windows: AvailabilityWindow[]
) {
  if (!memberTimezone) return true;

  const start = zonedDateTimeParts(slot.startUnix, memberTimezone);
  const end = zonedDateTimeParts(slot.endUnix, memberTimezone);
  if (start.date !== end.date) return false;

  // A member can set several blocks for one day (e.g. 09:00–12:00 and
  // 14:00–17:00), so the slot has to fit inside ANY one of them — `.some`,
  // not `.find`. This used to take only the first matching window, which
  // meant a second block saved fine and was then silently ignored by every
  // search.
  //
  // Fitting entirely within ONE block is the requirement, not covering the
  // union: a slot spanning 11:30–14:30 crosses the member's lunch break and
  // must be rejected even though both ends land inside some block.
  return windows
    .filter((w) => w.dayOfWeek === dayOfWeek(start.date))
    .some((w) => start.time >= w.startTime && end.time <= w.endTime);
}


function shortZoneName(date: Date, timezone: string) {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: timezone,
    timeZoneName: "short",
  }).formatToParts(date);
  return parts.find((p) => p.type === "timeZoneName")?.value ?? timezone;
}

/** Formats a unix-seconds slot start/end for display in `timezone`, e.g.
 * "Wed Aug 19, 12:00 PM–1:00 PM PDT". Both ends always carry AM/PM — omitting
 * it on the start (as a "12:00–1:00 PM" style would) is ambiguous for any
 * slot crossing noon or midnight. Formats straight from the UTC instant — no
 * intermediate toZonedTime() shift, which would double-convert. */
export function formatSlotRange(startUnix: number, endUnix: number, timezone: string) {
  const start = new Date(startUnix * 1000);
  const end = new Date(endUnix * 1000);

  const datePart = formatInTimeZone(start, timezone, "EEE MMM d");
  const startPart = formatInTimeZone(start, timezone, "h:mm a");
  const endPart = formatInTimeZone(end, timezone, "h:mm a");
  const zonePart = shortZoneName(start, timezone);

  return `${datePart}, ${startPart}–${endPart} ${zonePart}`;
}
